name: mixins_tests_bug
description: A Coverage Bug
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
